# Generated by Django 5.0.2 on 2024-02-20 06:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openapp', '0003_chat_user_alter_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='id',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
