# Generated by Django 5.0.2 on 2024-02-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openapp', '0005_rename_chat_id_chat_chat_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_room_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
