# Generated by Django 5.0.2 on 2024-02-22 03:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openapp', '0006_alter_chat_chat_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='id',
            field=models.BigAutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_room_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
