# Generated by Django 5.0.2 on 2024-03-18 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openapp', '0006_chat_id_alter_chat_chat_room_id'),
        ('openapp', '0006_remove_chat_id_alter_chat_chat_room_id'),
        ('openapp', '0007_chat_id_alter_chat_chat_room_id'),
    ]

    operations = [
    ]
